version: '3.7'

services:

  asterisk:
    platform: linux/amd64
    image: mlan/asterisk:full
    networks: 
      - freetalkbot
    ports:
      - 6569:4569/udp
      - 6050:5060/udp
      - 10000-10099:10000-10099/udp
    cap_add:
      - sys_ptrace                          # Only here to help testing
      - net_admin                           # Allow NFT, used by AutoBan
      - net_raw                             # Allow NFT, used by AutoBan
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}      # Logging
      - HOSTNAME=asterisk.docker.localhost
    volumes:
      - asterisk-conf:/srv                      # Persistent storage
      - ./asterisk/container-config:/etc/asterisk
      - ./pulse:/run/pulse:rshared          # Use host audio
      - /etc/localtime:/etc/localtime:ro    # Use host timezone    

  gobot_voip:
    build:
      context: .
      args:
        - SQL_DB_FILE_NAME=${SQL_DB_FILE_NAME}
    platform: linux/amd64
    #stdin_open: true
    #tty: true
    networks: 
      - freetalkbot
    command: ["freetalkbot", "init", "-c", "audio"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - app_data:/app/

  gobot_whatsapp:
    build:
      context: .
      args:
        - SQL_DB_FILE_NAME=${SQL_DB_FILE_NAME}
    platform: linux/amd64
    #stdin_open: true
    #tty: true
    networks: 
      - freetalkbot
    command: ["freetalkbot", "init", "-c", "whatsapp"]
    ports:
      - "443:443"
      - "5034:5034"
    env_file:
      - .env
    volumes:
      - app_data:/app/

  rasa:
    build:
      context: ./rasa
    env_file:
      - .env
    volumes:
      - ./rasa:/app
    command: 
      - run
      - --enable-api 
      - --cors 
      - "*"
    ports:
      - "5005:5005"
    networks:
      - freetalkbot

  rasa-actions-server:
    image: khalosa/rasa-aarch64:3.5.2
    env_file:
      - .env
    volumes:
      - ./rasa:/app
    command: 
      - run 
      - actions
    ports:
      - "5055:5055"
    networks:
      - freetalkbot

volumes:
  asterisk-conf:
  app_data:

networks:
  freetalkbot:
    driver: bridge