version: '3.0'

services:
  asterisk:
    platform: linux/amd64
    image: mlan/asterisk:full
    network_mode: host
    cap_add:
      - sys_ptrace
      - net_admin
      - net_raw
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}
      - HOSTNAME=asterisk.docker.localhost
    volumes:
      - asterisk-conf:/srv
      - ./asterisk/container-config:/etc/asterisk
      - ./pulse:/run/pulse:rshared
      - /etc/localtime:/etc/localtime:ro

  rasa:
    image: khalosa/rasa-aarch64:3.5.2
    volumes:
      - ./rasa:/app
    command: 
      - run 
      - --enable-api 
      - --cors 
      - "*"
    ports:
      - "5005:5005"
    network_mode: bridge

  rasa-actions-server:
    build:
      context: ./rasa
    volumes:
      - ./rasa:/app
      - ./rasa/models:/app/models
      - ./rasa/config:/app/config
    command: 
      - run 
      - actions
    ports:
      - "5055:5055"
    network_mode: bridge

volumes:
  asterisk-conf:
